####################################################################
#Tasklist: Debian/Ubuntu Update automation
#Description: Updates Debian/Ubuntu nodes using ansible
#Author: Peter Potvin
###################################################################
- hosts: debian-buster
  become: true

  tasks:
    - name: "Updating and upgrading system packages"
      apt: 
        update_cache: yes
        cache_valid_time: 3600
        upgrade: safe

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: Check if a reboot is needed on all servers
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot the box if kernel updated
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 150
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists

