- hosts: debian
  become: true

  tasks:
    - name: "Updating and upgrading system packages"
      apt: 
        update_cache: yes
        cache_valid_time: 3600
        upgrade: safe

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes