####################################################################
#Tasklist: Debian Wireguard Install Automation
#Description: Installs Wireguard on Debian nodes using ansible
#Author: Peter Potvin
#Email: (REDACTED)
#Revision 1 - 8 May 2021
###################################################################
- hosts: all
  become: true
  gather_facts: yes

  tasks:
  # Install Packages
    - name: "Updating and upgrading system packages"
      apt: 
        update_cache: yes
        cache_valid_time: 3600
        upgrade: safe

  # Install Wireguard
    - name: Copy scripts directory to remote system
      copy: 
        src: /home/sysadmin/ansible/scripts/
        dest: "/home/sysadmin/ansible/scripts/"
        mode: 0777

    - name: Execute Wireguard install script on remote system
      command: bash /home/sysadmin/ansible/scripts/debian10-wireguard-install.sh

  # Copy Wireguard configurations
    - name: Copy Wireguard configuration to 
      when: inventory_hostname == ''
      copy:
        src: /home/sysadmin/ansible/server-configurations/wg0.conf
        dest: /etc/wireguard/wg0.conf
        owner: root
      notify:
        - restart wg-quick@wg0

  handlers:
    - name: restart wg-quick@wg0
      service:
        name=wg-quick@wg0
        state=restarted