####################################################################
#Tasklist: CentOS 7 Update automation
#Description: Updates CentOS 7 nodes using ansible
#Author: Peter Potvin
#Email: (REDACTED)
#Revision 1 - 8 May 2021
###################################################################
- hosts: centos-7
  gather_facts: true
  become: true
  vars_files:
    - vars/default.yml

  tasks:
  # Upgrade system packages
    - name: upgrade packages via yum
      yum:
        name: "{{ yum_name }}"
        state: "{{ yum_state }}"
      register: yumcommandout
      when:
        - (ansible_facts['distribution_major_version'] == '7')

    - name: Print errors if yum failed
      debug:
        msg: "yum command produced errors"
      when: yumcommandout is not defined