create_user: sysadmin
# Ansible SSH Key
copy_local_key_1: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
# sysadmin SSH Key
copy_local_key_2: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa2.pub') }}"
sys_packages: ['yum-utils', 'epel-release', 'sudo', 'git', 'wget', 'curl', 'python3', 'python3-pip', 'tmux', 'nmap-ncat', 'bc', 'rsync', 'rpm-build', 'gcc', 'gcc-c++', 'make', 'glibc-devel', 'ca-certificates', 'gnupg2','flex', 'bison', 'libssh-devel', 'ncurses', 'readline', 'autoconf', 'automake', 'dos2unix', 'nload']
yum_name: "*"
yum_state:  latest