####################################################################
#Tasklist: Debian BIRD2 Install Automation
#Description: Installs BIRD2 on Debian nodes using ansible
#Author: Peter Potvin
#Email: (REDACTED)
#Revision 1 - 8 May 2021
###################################################################
- hosts: all
  become: true
  gather_facts: yes

  tasks:
  # Install Packages
    - name: "Updating and upgrading system packages"
      apt: 
        update_cache: yes
        cache_valid_time: 3600
        upgrade: safe

  # Install BIRD2
    - name: Copy scripts directory to remote system
      copy: 
        src: /home/sysadmin/ansible/scripts/
        dest: "/home/sysadmin/ansible/scripts/"
        mode: 0777

    - name: Execute BIRD2 install script on remote system
      command: bash /home/sysadmin/ansible/scripts/debian10-bird2-install.sh

  # Copy BIRD2 configurations
    - name: Copy BIRD2 configuration to 
      when: inventory_hostname == ''
      copy:
        src: /home/sysadmin/ansible/server-configurations/bird.conf
        dest: /etc/bird/bird.conf
        owner: bird
      notify:
        - restart bird

  handlers:
    - name: restart bird
      service:
        name=bird
        state=restarted